language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

matrix:
    allow_failures:
        - go: tip

install:
  - go get -t -v ./...

script:
  - make test

after_success:
  - goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN
